//! Games Syrup can name before it has ever seen them.
//!
//! Only public, stable facts: titles, executable names, genres, Steam app
//! ids, where the game's wiki's MediaWiki API lives. The catalog is a head
//! start, never a requirement: any other game is recognised as "a new game"
//! and learned from scratch.

use syrup_core::Hat;

#[derive(Debug, Clone, Copy)]
pub struct CatalogEntry {
    pub id: &'static str,
    pub title: &'static str,
    pub aliases: &'static [&'static str],
    /// Executable file names, any case, `.exe` optional.
    pub executables: &'static [&'static str],
    pub genres: &'static [&'static str],
    pub steam_app: Option<u32>,
    /// The MediaWiki `api.php` of the game's community wiki, when known.
    pub wiki_api: Option<&'static str>,
    /// The English Wikipedia article title.
    pub wikipedia: Option<&'static str>,
    /// A hat that suits the game better than its genres would pick.
    pub hat: Option<Hat>,
}

const fn game(
    id: &'static str,
    title: &'static str,
    aliases: &'static [&'static str],
    executables: &'static [&'static str],
    genres: &'static [&'static str],
    steam_app: Option<u32>,
    wiki_api: Option<&'static str>,
    wikipedia: Option<&'static str>,
) -> CatalogEntry {
    CatalogEntry { id, title, aliases, executables, genres, steam_app, wiki_api, wikipedia, hat: None }
}

pub const CATALOG: &[CatalogEntry] = &[
    CatalogEntry {
        hat: Some(Hat::SyrupCap),
        ..game(
            "maplestory",
            "MapleStory",
            &["maple story", "maplestory global", "gms"],
            &["MapleStory.exe"],
            &["mmorpg", "side_scroller", "fantasy"],
            Some(216150),
            Some("https://maplestory.fandom.com/api.php"),
            Some("MapleStory"),
        )
    },
    game(
        "minecraft",
        "Minecraft",
        &[],
        &["Minecraft.Windows.exe", "MinecraftLauncher.exe"],
        &["sandbox", "survival", "open_world"],
        None,
        Some("https://minecraft.wiki/api.php"),
        Some("Minecraft"),
    ),
    game(
        "league-of-legends",
        "League of Legends",
        &["lol"],
        &["League of Legends.exe"],
        &["moba", "strategy"],
        None,
        Some("https://leagueoflegends.fandom.com/api.php"),
        Some("League of Legends"),
    ),
    game(
        "valorant",
        "VALORANT",
        &[],
        &["VALORANT-Win64-Shipping.exe"],
        &["shooter", "fps", "tactical"],
        None,
        Some("https://valorant.fandom.com/api.php"),
        Some("Valorant"),
    ),
    game(
        "counter-strike-2",
        "Counter-Strike 2",
        &["cs2", "counter strike 2"],
        &["cs2.exe"],
        &["shooter", "fps", "tactical"],
        Some(730),
        Some("https://counterstrike.fandom.com/api.php"),
        Some("Counter-Strike 2"),
    ),
    game(
        "fortnite",
        "Fortnite",
        &[],
        &["FortniteClient-Win64-Shipping.exe"],
        &["shooter", "battle_royale"],
        None,
        Some("https://fortnite.fandom.com/api.php"),
        Some("Fortnite"),
    ),
    game(
        "elden-ring",
        "ELDEN RING",
        &["elden ring"],
        &["eldenring.exe"],
        &["soulslike", "action_rpg", "open_world"],
        Some(1245620),
        Some("https://eldenring.fandom.com/api.php"),
        Some("Elden Ring"),
    ),
    game(
        "dark-souls-3",
        "DARK SOULS III",
        &["dark souls 3", "dark souls iii"],
        &["DarkSoulsIII.exe"],
        &["soulslike", "action_rpg"],
        Some(374320),
        Some("https://darksouls.fandom.com/api.php"),
        Some("Dark Souls III"),
    ),
    game(
        "stardew-valley",
        "Stardew Valley",
        &[],
        &["Stardew Valley.exe", "StardewValley.exe"],
        &["farming", "life_sim", "cozy"],
        Some(413150),
        Some("https://stardewvalleywiki.com/mediawiki/api.php"),
        Some("Stardew Valley"),
    ),
    game(
        "hollow-knight",
        "Hollow Knight",
        &[],
        &["hollow_knight.exe"],
        &["metroidvania", "action", "platformer"],
        Some(367520),
        Some("https://hollowknight.fandom.com/api.php"),
        Some("Hollow Knight"),
    ),
    game(
        "hades",
        "Hades",
        &[],
        &["Hades.exe"],
        &["roguelike", "action", "hack_and_slash"],
        Some(1145360),
        Some("https://hades.fandom.com/api.php"),
        Some("Hades (video game)"),
    ),
    game(
        "hades-2",
        "Hades II",
        &["hades 2"],
        &["Hades2.exe"],
        &["roguelike", "action", "hack_and_slash"],
        Some(1145350),
        Some("https://hades.fandom.com/api.php"),
        Some("Hades II"),
    ),
    game(
        "slay-the-spire",
        "Slay the Spire",
        &[],
        &["SlayTheSpire.exe"],
        &["deckbuilder", "card", "roguelike"],
        Some(646570),
        Some("https://slay-the-spire.fandom.com/api.php"),
        Some("Slay the Spire"),
    ),
    game(
        "balatro",
        "Balatro",
        &[],
        &["Balatro.exe"],
        &["card", "poker", "roguelike"],
        Some(2379780),
        Some("https://balatrogame.fandom.com/api.php"),
        Some("Balatro"),
    ),
    game(
        "hearthstone",
        "Hearthstone",
        &[],
        &["Hearthstone.exe"],
        &["card", "deckbuilder"],
        None,
        Some("https://hearthstone.fandom.com/api.php"),
        Some("Hearthstone"),
    ),
    game(
        "terraria",
        "Terraria",
        &[],
        &["Terraria.exe"],
        &["sandbox", "action", "side_scroller"],
        Some(105600),
        Some("https://terraria.wiki.gg/api.php"),
        Some("Terraria"),
    ),
    game(
        "genshin-impact",
        "Genshin Impact",
        &["genshin"],
        &["GenshinImpact.exe", "YuanShen.exe"],
        &["action_rpg", "open_world", "fantasy"],
        None,
        Some("https://genshin-impact.fandom.com/api.php"),
        Some("Genshin Impact"),
    ),
    game(
        "diablo-4",
        "Diablo IV",
        &["diablo 4", "diablo iv"],
        &["Diablo IV.exe"],
        &["action_rpg", "hack_and_slash", "dungeon"],
        Some(2344520),
        Some("https://diablo.fandom.com/api.php"),
        Some("Diablo IV"),
    ),
    game(
        "path-of-exile",
        "Path of Exile",
        &["poe"],
        &["PathOfExile.exe", "PathOfExile_x64.exe", "PathOfExileSteam.exe", "PathOfExile_x64Steam.exe"],
        &["action_rpg", "hack_and_slash", "dungeon"],
        Some(238960),
        Some("https://www.poewiki.net/w/api.php"),
        Some("Path of Exile"),
    ),
    game(
        "world-of-warcraft",
        "World of Warcraft",
        &["wow"],
        &["Wow.exe", "WowClassic.exe"],
        &["mmorpg", "fantasy"],
        None,
        Some("https://wowpedia.fandom.com/api.php"),
        Some("World of Warcraft"),
    ),
    game(
        "overwatch-2",
        "Overwatch 2",
        &["overwatch"],
        &["Overwatch.exe"],
        &["shooter", "fps", "hero_shooter"],
        Some(2357570),
        Some("https://overwatch.fandom.com/api.php"),
        Some("Overwatch 2"),
    ),
    game(
        "apex-legends",
        "Apex Legends",
        &["apex"],
        &["r5apex.exe", "r5apex_dx12.exe"],
        &["shooter", "battle_royale"],
        Some(1172470),
        Some("https://apexlegends.fandom.com/api.php"),
        Some("Apex Legends"),
    ),
    game(
        "rocket-league",
        "Rocket League",
        &[],
        &["RocketLeague.exe"],
        &["sports", "racing", "football"],
        Some(252950),
        Some("https://rocketleague.fandom.com/api.php"),
        Some("Rocket League"),
    ),
    game(
        "forza-horizon-5",
        "Forza Horizon 5",
        &[],
        &["ForzaHorizon5.exe"],
        &["racing", "open_world"],
        Some(1551360),
        Some("https://forzamotorsport.fandom.com/api.php"),
        Some("Forza Horizon 5"),
    ),
    game(
        "civilization-6",
        "Sid Meier's Civilization VI",
        &["civilization vi", "civ 6", "civ vi"],
        &["CivilizationVI.exe", "CivilizationVI_DX12.exe"],
        &["strategy", "4x", "turn_based"],
        Some(289070),
        Some("https://civilization.fandom.com/api.php"),
        Some("Civilization VI"),
    ),
    game(
        "starcraft-2",
        "StarCraft II",
        &["starcraft 2", "sc2"],
        &["SC2_x64.exe", "SC2.exe"],
        &["strategy", "rts", "space"],
        None,
        Some("https://starcraft.fandom.com/api.php"),
        Some("StarCraft II"),
    ),
    game(
        "dota-2",
        "Dota 2",
        &[],
        &["dota2.exe"],
        &["moba", "strategy"],
        Some(570),
        Some("https://dota2.fandom.com/api.php"),
        Some("Dota 2"),
    ),
    game(
        "among-us",
        "Among Us",
        &[],
        &["Among Us.exe"],
        &["social_deduction", "mystery"],
        Some(945360),
        Some("https://among-us.fandom.com/api.php"),
        Some("Among Us"),
    ),
    game(
        "sea-of-thieves",
        "Sea of Thieves",
        &[],
        &["SoTGame.exe"],
        &["pirate", "adventure", "open_world"],
        Some(1172620),
        Some("https://seaofthieves.fandom.com/api.php"),
        Some("Sea of Thieves"),
    ),
    game(
        "subnautica",
        "Subnautica",
        &[],
        &["Subnautica.exe"],
        &["survival", "open_world", "exploration"],
        Some(264710),
        Some("https://subnautica.fandom.com/api.php"),
        Some("Subnautica"),
    ),
    game(
        "phasmophobia",
        "Phasmophobia",
        &[],
        &["Phasmophobia.exe"],
        &["horror", "investigation"],
        Some(739630),
        Some("https://phasmophobia.fandom.com/api.php"),
        Some("Phasmophobia"),
    ),
    game(
        "no-mans-sky",
        "No Man's Sky",
        &["no mans sky"],
        &["NMS.exe"],
        &["space", "survival", "open_world"],
        Some(275850),
        Some("https://nomanssky.fandom.com/api.php"),
        Some("No Man's Sky"),
    ),
    game(
        "baldurs-gate-3",
        "Baldur's Gate 3",
        &["baldurs gate 3", "bg3"],
        &["bg3.exe", "bg3_dx11.exe"],
        &["rpg", "fantasy", "turn_based"],
        Some(1086940),
        Some("https://baldursgate.fandom.com/api.php"),
        Some("Baldur's Gate 3"),
    ),
    game(
        "cyberpunk-2077",
        "Cyberpunk 2077",
        &[],
        &["Cyberpunk2077.exe"],
        &["action_rpg", "shooter", "open_world"],
        Some(1091500),
        Some("https://cyberpunk.fandom.com/api.php"),
        Some("Cyberpunk 2077"),
    ),
    game(
        "witcher-3",
        "The Witcher 3: Wild Hunt",
        &["witcher 3", "the witcher 3"],
        &["witcher3.exe"],
        &["action_rpg", "open_world", "fantasy"],
        Some(292030),
        Some("https://witcher.fandom.com/api.php"),
        Some("The Witcher 3: Wild Hunt"),
    ),
    game(
        "skyrim",
        "The Elder Scrolls V: Skyrim",
        &["skyrim", "skyrim special edition"],
        &["SkyrimSE.exe", "TESV.exe"],
        &["rpg", "open_world", "fantasy"],
        Some(489830),
        Some("https://elderscrolls.fandom.com/api.php"),
        Some("The Elder Scrolls V: Skyrim"),
    ),
    game(
        "celeste",
        "Celeste",
        &[],
        &["Celeste.exe"],
        &["platformer"],
        Some(504230),
        Some("https://celestegame.fandom.com/api.php"),
        Some("Celeste (video game)"),
    ),
    game(
        "monster-hunter-world",
        "Monster Hunter: World",
        &["monster hunter world", "mhw"],
        &["MonsterHunterWorld.exe"],
        &["action_rpg", "hunting"],
        Some(582010),
        Some("https://monsterhunter.fandom.com/api.php"),
        Some("Monster Hunter: World"),
    ),
    game(
        "helldivers-2",
        "HELLDIVERS 2",
        &["helldivers 2"],
        &["helldivers2.exe"],
        &["shooter", "military"],
        Some(553850),
        Some("https://helldivers.fandom.com/api.php"),
        Some("Helldivers 2"),
    ),
    game(
        "palworld",
        "Palworld",
        &[],
        &["Palworld-Win64-Shipping.exe"],
        &["survival", "open_world"],
        Some(1623730),
        Some("https://palworld.fandom.com/api.php"),
        Some("Palworld"),
    ),
    game(
        "valheim",
        "Valheim",
        &[],
        &["valheim.exe"],
        &["survival", "open_world"],
        Some(892970),
        Some("https://valheim.fandom.com/api.php"),
        Some("Valheim"),
    ),
    game(
        "dead-cells",
        "Dead Cells",
        &[],
        &["deadcells.exe"],
        &["roguelike", "metroidvania", "action"],
        Some(588650),
        Some("https://deadcells.fandom.com/api.php"),
        Some("Dead Cells"),
    ),
    game(
        "vampire-survivors",
        "Vampire Survivors",
        &[],
        &["VampireSurvivors.exe"],
        &["roguelike", "horror"],
        Some(1794680),
        Some("https://vampire-survivors.fandom.com/api.php"),
        Some("Vampire Survivors"),
    ),
    game(
        "factorio",
        "Factorio",
        &[],
        &["factorio.exe"],
        &["strategy", "automation"],
        Some(427520),
        Some("https://wiki.factorio.com/api.php"),
        Some("Factorio"),
    ),
    game(
        "rimworld",
        "RimWorld",
        &[],
        &["RimWorldWin64.exe"],
        &["strategy", "colony_sim", "space"],
        Some(294100),
        Some("https://rimworldwiki.com/api.php"),
        Some("RimWorld"),
    ),
    game(
        "lethal-company",
        "Lethal Company",
        &[],
        &["Lethal Company.exe"],
        &["horror", "survival"],
        Some(1966720),
        Some("https://lethal-company.fandom.com/api.php"),
        Some("Lethal Company"),
    ),
    game(
        "deep-rock-galactic",
        "Deep Rock Galactic",
        &["drg"],
        &["FSD-Win64-Shipping.exe", "FSD.exe"],
        &["shooter", "space"],
        Some(548430),
        Some("https://deeprockgalactic.fandom.com/api.php"),
        Some("Deep Rock Galactic"),
    ),
    game(
        "roblox",
        "Roblox",
        &[],
        &["RobloxPlayerBeta.exe"],
        &["sandbox"],
        None,
        Some("https://roblox.fandom.com/api.php"),
        Some("Roblox"),
    ),
    game(
        "geometry-dash",
        "Geometry Dash",
        &[],
        &["GeometryDash.exe"],
        &["platformer", "rhythm"],
        Some(322170),
        Some("https://geometry-dash.fandom.com/api.php"),
        Some("Geometry Dash"),
    ),
    game(
        "minesweeper",
        "Minesweeper",
        &["minesweeper online"],
        &[],
        &["puzzle"],
        None,
        None,
        Some("Minesweeper (video game)"),
    ),
    game(
        "solitaire",
        "Solitaire",
        &["microsoft solitaire collection", "klondike"],
        &["Solitaire.exe"],
        &["card"],
        None,
        None,
        Some("Microsoft Solitaire Collection"),
    ),
];

pub fn by_id(id: &str) -> Option<&'static CatalogEntry> {
    CATALOG.iter().find(|e| e.id == id)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn catalog_ids_are_unique_and_tidy() {
        let mut ids: Vec<&str> = CATALOG.iter().map(|e| e.id).collect();
        ids.sort();
        let n = ids.len();
        ids.dedup();
        assert_eq!(ids.len(), n);
        for e in CATALOG {
            assert!(e.id.chars().all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '-'), "{}", e.id);
            assert!(!e.genres.is_empty(), "{}", e.id);
        }
        assert_eq!(by_id("maplestory").unwrap().hat, Some(Hat::SyrupCap));
    }
}
